version: '3.8'

services:
  iot1-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped


